# Generated by Django 4.1.4 on 2022-12-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="channel",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="youtube channel id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="playlist",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="youtube playlist id",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_id",
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.CharField(
                max_length=255,
                primary_key=True,
                serialize=False,
                verbose_name="youtube video id",
            ),
        ),
    ]
