# Generated by Django 4.1.4 on 2022-12-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0002_channel_playlist_remove_video_video_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="played",
            field=models.BooleanField(
                default=False, verbose_name="Video played Status"
            ),
        ),
    ]
