# Generated by Django 4.1.4 on 2022-12-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0003_video_played"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="id",
            field=models.CharField(
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="youtube channel id",
            ),
        ),
    ]
