# Generated by Django 4.1.4 on 2022-12-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0004_alter_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="thumbnail",
            field=models.CharField(
                default="", max_length=255, verbose_name="youtube Channel Thumbnail"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="title",
            field=models.CharField(
                default="", max_length=255, verbose_name="youtube Channel title"
            ),
        ),
    ]
