# Generated by Django 4.1.4 on 2022-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0005_channel_thumbnail_channel_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="playlist",
        ),
        migrations.AddField(
            model_name="channel",
            name="plid",
            field=models.CharField(
                default="", max_length=255, verbose_name="youtube playlist id"
            ),
        ),
    ]
