# Generated by Django 4.1.4 on 2022-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0006_delete_playlist_channel_plid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="plid",
            field=models.CharField(max_length=255, verbose_name="youtube playlist id"),
        ),
    ]
