# Generated by Django 4.1.4 on 2022-12-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0007_alter_channel_plid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="played",
        ),
    ]
