# Generated by Django 4.1.4 on 2022-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0008_remove_video_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="date_posted",
            field=models.CharField(
                default="", max_length=255, verbose_name="Youtube Video Posted Date"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="id",
            field=models.CharField(
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Youtube channel id",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="plid",
            field=models.CharField(
                max_length=255, verbose_name="Youtube Channel Playlist id"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="thumbnail",
            field=models.CharField(
                default="", max_length=255, verbose_name="Youtube Channel Thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="title",
            field=models.CharField(
                default="", max_length=255, verbose_name="Youtube Channel Title"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.CharField(
                max_length=255,
                primary_key=True,
                serialize=False,
                verbose_name="Youtube Video id",
            ),
        ),
    ]
