# Generated by Django 4.1.4 on 2022-12-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0009_video_date_posted_alter_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.CharField(
                default="", max_length=255, verbose_name="Youtube Video Thumbnail"
            ),
        ),
    ]
