# Generated by Django 4.1.4 on 2022-12-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0011_video_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(
                default="", max_length=255, verbose_name="Youtube Video Title"
            ),
        ),
    ]
