# Generated by Django 4.1.4 on 2022-12-27 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0012_video_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
