# Generated by Django 4.1.4 on 2022-12-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0013_alter_video_date_posted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["date_posted"]},
        ),
    ]
