# Generated by Django 4.1.4 on 2022-12-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0014_alter_channel_options_alter_video_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Settings Key"
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=255, verbose_name="Settings Key"),
                ),
            ],
        ),
    ]
