# Generated by Django 4.1.4 on 2022-12-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0016_settings_key_verbose_settings_value_verbose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="audio_downloaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="hires_downloaded",
            field=models.BooleanField(default=False),
        ),
    ]
