# Generated by Django 4.1.4 on 2022-12-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0017_video_audio_downloaded_video_hires_downloaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="mark_played",
            field=models.BooleanField(default=False),
        ),
    ]
