# Generated by Django 4.1.4 on 2022-12-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0018_video_mark_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.CharField(
                default="", max_length=255, verbose_name="Youtube Video Duration"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="audio_downloaded",
            field=models.BooleanField(
                default=False, verbose_name="Youtube Audio Downloaded"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="youtube.channel",
                verbose_name="Youtube Channel Publisher",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="hires_downloaded",
            field=models.BooleanField(
                default=False, verbose_name="Youtube High Resolution Downloaded"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="mark_played",
            field=models.BooleanField(
                default=False, verbose_name="Youtube Video Maked as played"
            ),
        ),
    ]
