# Generated by Django 4.1.4 on 2023-01-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0019_video_duration_alter_video_audio_downloaded_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="mark_played",
            new_name="marked_played",
        ),
    ]
