# Generated by Django 4.1.4 on 2023-01-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0020_rename_mark_played_video_marked_played"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Settings",
            new_name="Setting",
        ),
    ]
