# Generated by Django 4.1.4 on 2023-01-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0021_rename_settings_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="is_bool",
            field=models.BooleanField(
                default=False, max_length=255, verbose_name="Setting Boolean Status"
            ),
        ),
    ]
