# Generated by Django 4.1.4 on 2023-01-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0022_setting_is_bool"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="has_options",
            field=models.BooleanField(
                default=False, verbose_name="Setting Has Options"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="is_bool",
            field=models.BooleanField(
                default=False, verbose_name="Setting Boolean Status"
            ),
        ),
    ]
