# Generated by Django 4.1.4 on 2023-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0024_option"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Option",
            new_name="SettingOption",
        ),
        migrations.AddField(
            model_name="channel",
            name="inititalized",
            field=models.BooleanField(
                default=False, verbose_name="Youtube Channel Initialized"
            ),
        ),
    ]
