# Generated by Django 4.1.4 on 2023-01-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0025_rename_option_settingoption_channel_inititalized"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="inititalized",
            new_name="initialized",
        ),
    ]
