# Generated by Django 4.1.4 on 2023-01-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0027_feedsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedsettings",
            name="hide_played",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feedsettings",
            name="feed_order",
            field=models.CharField(
                choices=[("CH", "Chronological"), ("RC", "Reverse Chronological")],
                default="CH",
                max_length=2,
            ),
        ),
    ]
