# Generated by Django 4.1.4 on 2023-01-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0028_feedsettings_hide_played_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settingoption",
            name="setting",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="marked_played",
            new_name="played",
        ),
        migrations.DeleteModel(
            name="Setting",
        ),
        migrations.DeleteModel(
            name="SettingOption",
        ),
    ]
